version: '3.7'

services:
  airflow:
    image: puckel/docker-airflow:1.10.9
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=n
      - FERNET_KEY=V6nya_2xNSdPFiduB_3RbdoJ0qPfl87dsZhgwH7PQOk=  # Replace with a secure fernet key
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./aws_utils:/usr/local/airflow/aws_utils

  spark-master:
    image: bitnami/spark:3
    container_name: spark-master
    ports:
      - "4040:4040"
      - "6066:6066"
      - "7077:7077"
      - "8050:8050"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8050

  spark-worker-1:
    image: bitnami/spark:3
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8051

  spark-worker-2:
    image: bitnami/spark:3
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8052

  spark-worker-3:
    image: bitnami/spark:3
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8053

  spark-submit:
    image: bitnami/spark:3
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - spark-worker-3
    volumes:
      - ./your-spark-job.jar:/opt/bitnami/spark/your-spark-job.jar
    command: >
      spark-submit
      --class com.example.YourSparkJob
      --master spark://spark-master:7077
      /opt/bitnami/spark/your-spark-job.jar
